import { useState } from "react";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "regenerator-runtime/runtime";
import Link from "next/link";

export default function Home({ Component, pageProps }) {
  const [title, setTitle] = useState("");
  const [price, setPrice] = useState("");
  const [thumb, setThumb] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    const data = {
      title,
      price,
      thumb
    };
    fetch(
      "https://ds4-cdrhouse.herokuapp.com/api/productos?title=" +
        data.title +
        "&price=" +
        data.price +
        "&thumbnail=" +
        data.thumb,
      {
        method: "post",
        body: JSON.stringify(data)
      }
    );
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form class="text-right border border-light p-5" onSubmit={handleSubmit}>
        <Form.Label htmlFor="name">
          Title:
          <input
            class="form-control"
            id="title"
            type="text"
            onChange={(e) => setTitle(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Price:
          <input
            class="form-control"
            id="price"
            type="text"
            onChange={(e) => setPrice(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Form.Label htmlFor="email">
          Thumbnail:
          <input
            class="form-control"
            id="thumb"
            type="text"
            onChange={(e) => setThumb(e.target.value)}
          />
        </Form.Label>
        <p></p>
        <Button type="submit">Send</Button>
      </Form>
      <Link href="/">
        <a>Volver al menú</a>
      </Link>
    </div>
  );
}
